# Generated by Django 3.2 on 2021-05-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0006_alter_account_ref_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='withdraw_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='ref_code',
            field=models.CharField(blank=True, default='244', max_length=50, null=True),
        ),
    ]
