# Generated by Django 3.2 on 2021-05-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0007_auto_20210507_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='referral_balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='ref_code',
            field=models.CharField(blank=True, default='961', max_length=50, null=True),
        ),
    ]
