# Generated by Django 3.2 on 2021-05-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0008_auto_20210507_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='investment_earnings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='ref_code',
            field=models.CharField(blank=True, default='893', max_length=50, null=True),
        ),
    ]
