# Generated by Django 3.2 on 2021-05-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0009_auto_20210507_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ref_code',
            field=models.CharField(blank=True, default='688', max_length=50, null=True),
        ),
    ]
