# Generated by Django 3.2 on 2021-05-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0021_alter_account_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='ref_code',
            field=models.CharField(blank=True, default='645', max_length=50, null=True),
        ),
    ]
