# Generated by Django 3.2 on 2021-05-12 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0022_auto_20210512_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ref_code',
            field=models.CharField(blank=True, default='456', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='RefferalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('recommended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recom_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
