# Generated by Django 3.2 on 2021-05-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0023_auto_20210512_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='deposited',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='ref_code',
            field=models.CharField(blank=True, default='511', max_length=50, null=True),
        ),
    ]
