# Generated by Django 3.2 on 2021-05-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0024_auto_20210513_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='refferalprofile',
            name='bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='ref_code',
            field=models.CharField(blank=True, default='742', max_length=50, null=True),
        ),
    ]
