# Generated by Django 3.2 on 2021-05-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0025_auto_20210513_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ref_code',
            field=models.CharField(blank=True, default='190', max_length=50, null=True),
        ),
    ]
