# Generated by Django 3.2 on 2021-05-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
