# Generated by Django 3.2 on 2021-05-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_investment_primary_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='with_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('complete', 'complete')], max_length=40, null=True),
        ),
    ]
