# Generated by Django 3.2 on 2021-05-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_investment_with_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='with_status',
        ),
        migrations.AddField(
            model_name='investment',
            name='p_with_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
