# Generated by Django 3.2 on 2021-05-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20210507_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='p_with_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
