# Generated by Django 3.2 on 2021-05-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_referalwithdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='referalwithdraw',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
