# Generated by Django 3.2 on 2021-05-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20210507_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
    ]
