# Generated by Django 3.2 on 2021-05-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
