# Generated by Django 3.2 on 2021-05-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_verificationcode_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default='341', max_length=50),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
