# Generated by Django 3.2 on 2021-05-12 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_alter_verificationcode_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='referalwithdraw',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='verificationcode',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='withdraw',
            options={'ordering': ['-date']},
        ),
    ]
