# Generated by Django 3.2 on 2021-05-17 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_auto_20210512_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='with_investment', to='manager.investment'),
        ),
    ]
