# Generated by Django 3.2 on 2021-05-22 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_alter_withdraw_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.packages'),
        ),
    ]
